# Links all files in docs to the README for Jekyll

name: Link

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          sed -i '1,/--- | ---/p;/<hr>/,$p' README.md
          ls docs | awk '{print "!["$0"](https://emoj.ml/"$0") | [https://emoj.ml/"$0"](https://emoj.ml/"$0")"}' >> README.md
          sed -i '/README.md/d' README.md
          sed -i '/_config.yml/d' README.md
          sed -i '/CNAME/d' README.md
          rm docs/README.md
          ln README.md docs/
          git config --global user.name 'Runner'
          git config --global user.email 'runner@users.noreply.github.com'
          git commit -am "Automatically link emoji"
          git push || echo "No emoji to update"
